version: '3.8'

services:
  flaskapp:
    build: .
    restart: always
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - ./:/app

volumes:
  db_data:


